apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: sword-api
    template:
        metadata:
            labels:
                app: sword-api
        spec:
            containers:
                - name: sword-api
                  image: sword-api-image:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: NODE_ENV
                        value: production
                      - name: DB_HOST
                        value: mysql
                      - name: DB_NAME
                        value: sword-db
                      - name: DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: username
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: password
---
apiVersion: v1
kind: Service
metadata:
    name: sword-api-service
spec:
    selector:
        app: sword-api
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 3000
